# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ftl < Formula
  desc "FTL - Faster Than Light deployment tool"
  homepage "https://github.com/yarlson/ftl"
  version "0.13.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/yarlson/ftl/releases/download/0.13.0/ftl_0.13.0_darwin_amd64.tar.gz"
      sha256 "70bbafc442e045e03cd05e591f25c07f85337441b1c07e454bec9af18eb3291a"

      def install
        bin.install "ftl"
      end
    end
    on_arm do
      url "https://github.com/yarlson/ftl/releases/download/0.13.0/ftl_0.13.0_darwin_arm64.tar.gz"
      sha256 "e295321109c7121d74fb993fd011eff6cb9fd61aa3d6dfbac1030c5269eca810"

      def install
        bin.install "ftl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yarlson/ftl/releases/download/0.13.0/ftl_0.13.0_linux_amd64.tar.gz"
        sha256 "62a2e7c17dd87558a7e4dacb3eb2e1d746aa7877f35623c180521af9973cc556"

        def install
          bin.install "ftl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yarlson/ftl/releases/download/0.13.0/ftl_0.13.0_linux_arm64.tar.gz"
        sha256 "435b711a3ce05710efa8676379ecd65cefb88db8366bad5a8e407ed1104a14d9"

        def install
          bin.install "ftl"
        end
      end
    end
  end

  test do
    system "#{bin}/ftl --version"
  end
end
