# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ftl < Formula
  desc "FTL - Faster Than Light deployment tool"
  homepage "https://github.com/yarlson/ftl"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/yarlson/ftl/releases/download/0.3.0/ftl_0.3.0_darwin_amd64.tar.gz"
      sha256 "e25fb6f282759ef776f63f719aa3b36bd20af791faefa9c4c88f48ea6128fb8b"

      def install
        bin.install "ftl"
      end
    end
    on_arm do
      url "https://github.com/yarlson/ftl/releases/download/0.3.0/ftl_0.3.0_darwin_arm64.tar.gz"
      sha256 "811e4e0ecaa269ddd796a3ffc8ab5b9b6e1cd7fe8f9b3c6421f8603cca6d73e1"

      def install
        bin.install "ftl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yarlson/ftl/releases/download/0.3.0/ftl_0.3.0_linux_amd64.tar.gz"
        sha256 "fc92c2da7433cc99428abf97b42ee9baf467d191c44a3b8c8721638560f4d1bd"

        def install
          bin.install "ftl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yarlson/ftl/releases/download/0.3.0/ftl_0.3.0_linux_arm64.tar.gz"
        sha256 "24db6251e021cfc164b82b30a49db1b4587071b9bc7c72b2a56bc81cb453a01b"

        def install
          bin.install "ftl"
        end
      end
    end
  end

  test do
    system "#{bin}/ftl --version"
  end
end
